name: Release Go Project

on:
    push:
        tags:
            - "*"

jobs:
    build:
        name: GoReleaser build
        runs-on: ubuntu-latest

        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: "1.21"
              id: go
            
            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@master
              with:
                version: latest
                args: release --rm-dist
                workdir: ./cmd/cli
              env:
                GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

